[project]
name = "ml-2026"
version = "0.1.0"
readme = "ReadMe.md"
requires-python = ">= 3.14"

dependencies = [
    "opencv-python",
    "pandas",
    "requests",
]
[dependency-groups]
dev = [
    "black",
    "isort",
    "mypy",
    "pre-commit",
    "pyright >= 1.1.408",
    "ruff",
]

[tool.black]
line-length = 100

[tool.isort]
float_to_top =            true
include_trailing_comma =  true
multi_line_output =       "VERTICAL_HANGING_INDENT"
line_length =             100

[tool.pyright]
# typeCheckingMode = "strict"
reportUninitializedInstanceVariable = true
reportUnknownVariableType = true
reportUnknownArgumentType = true

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "E4", "E7", "E9", "A", "ARG", "ASYNC", "B", "BLE", "C", "C4", "C90", "COM",
    "DTZ", "E", "EM", "EXE", "F", "FBT", "FIX", "FURB", "G", "ICN", "INT", "ISC",
    "LOG", "N", "NPY", "PD", "PERF", "PIE", "PL", "PTH", "PYI", "Q", "RET", "RSE", "RUF",
    "SIM", "SLF", "SLOT", "TCH", "TID", "TRY", "UP", "W", "YTT",
]

[tool.uv]
default-groups = ["dev"]
